### ISSUE TITLE
Cannot connect to docker container

### ISSUE THREAD

**Issue by M-Stenzel** [owntracks/frontend#128]
After not being successful in manual installation I tried to use the docker solution (pulled today, latest container version).

This is my docker-compose.yml file

```
version: "3"

services:
  owntracks-ui:
    image: owntracks/frontend
    ports:
      - 1111:80
    volumes:
      - ./config.js:/usr/share/nginx/html/config/config.js
    environment:
      - SERVER_HOST=1.1.1.1 (redacted)
      - SERVER_PORT=8083
      - LISTEN_PORT=1111 (redacted)
    restart: unless-stopped

```

I verified that the container runs as expected

```
netstat -tulpn | grep 1111

tcp        0      0 0.0.0.0:1111           0.0.0.0:*               LISTEN      19112/docker-proxy  
tcp6       0      0 :::1111                :::*                    LISTEN      19119/docker-proxy

```

When I try to connect with a browser it tells me that the connection is being refused (ERR_CONNECTION_REFUSED).

_docker logs CONTAINER_

does not show me any logs.

Any ideas?

Martin.
