### ISSUE TITLE
Allow docker container to run as non-root user

### ISSUE THREAD

**Issue by thecodygriffin** [owntracks/frontend#158]
Whenever I try to run the owntracks/front image as a docker container using the user directive, the container fails to start due to a permissions issue with nginx.

`/bin/sh: can't create /etc/nginx/nginx.conf: Permission denied`

It appears that within the container, an nginx user is being used to run the nginx process. My expectation would be that the container user, whether root or a non-root user specificed in the docker command or docker-compose file would be used to run the nginx process.

For reference, I am specifying the user via the user directive of my docker-compose file...

```
  owntracks_frontend:
    image: owntracks/frontend
    user: 121:1001
    container_name: owntracks_frontend
    restart: unless-stopped
    environment:
      - SERVER_HOST=owntracks_recorder
      - SERVER_PORT=8083
    volumes:
      - /path/to/config/config.js:/usr/share/nginx/html/config/config.js
    networks:
      - owntracks_net
```
Would it be possible to have the Dockerfile include PUID and PGID environment variables that are passed when the nginx process is started?

For example, something along the lines of ...
```
  owntracks_frontend:
    image: owntracks/frontend
    container_name: owntracks_frontend
    restart: unless-stopped
    environment:
      - PUID=121
      - PGUID=1001
      - SERVER_HOST=owntracks_recorder
      - SERVER_PORT=8083
    volumes:
      - /path/to/config/config.js:/usr/share/nginx/html/config/config.js
    networks:
      - owntracks_net
```

**Comment by thecodygriffin** [comment]
After looking into this further, my previous suggestion doesn't seem like it would be a viable approach.

Per [Running nginx as a non-root user](https://hub.docker.com/_/nginx#:~:text=Running%20nginx%20as%20a%20non%2Droot%20user) section of the [nginx official image](https://hub.docker.com/_/nginx) page on dockerhub, it appears that the /etc/nginx/nginx.conf file must be updated to allow a container to be run as non-root.

Given that this file is generated from the nginx.tmpl file that is part of the owntracks/frontend image, I don't believe that I can simply map a volume to an updated version of it. If that is accurate, what I'd recommend is that the /etc/nginx/nginx.tmpl file referenced in the Dockerfile that is copied into the image have the following directive added:
```
include /etc/nginx/conf.d/*.conf; 
```
This would allow me to map a volume to /etc/nginx/conf.d/ as follows:
```
volumes:
   - /path/to/nginx/conf.d:/etc/nginx/conf.d
```
I could then define a nonroot_user.conf with the following directives per the aformentioned nginx dockerhub documentation.
```
pid        /tmp/nginx.pid;

http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;
}
```
What do you think? Is this feasible and something worth doing?

**Comment by thecodygriffin** [comment]
Another update...

I have found a work-around for the current Dockerfile as of this comment.

I have to mapped both the /etc/nginx/nginx.tmpl file and the /etc/nginx/nginx.conf file to a volume.
```
  owntracks_frontend:
    image: owntracks/frontend
    user: 121:1001
    container_name: owntracks_frontend
    restart: unless-stopped
    environment:
      - SERVER_HOST=owntracks_recorder
      - SERVER_PORT=8083
    volumes:
      - /path/to/owntracks/frontend/config/config.js:/usr/share/nginx/html/config/config.js
      - /path/to/owntracks/frontend/nginx/nginx.tmpl:/etc/nginx/nginx.tmpl
      - /path/to/owntracks/frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - owntracks_net
```
I then took the the current [nginx.tmpl from github](https://github.com/owntracks/frontend/blob/f8d1d0dea37a624ebac214f1524698f64d93cae1/docker/nginx.tmpl) and uploaded it to my mapped volume location of /path/to/owntracks/frontend/nginx/nginx.tmpl.
```
worker_processes 1;
events {
    worker_connections 1024;
}
http {
    upstream otrecorder {
        server ${SERVER_HOST}:${SERVER_PORT};
    }
    server {
        listen ${LISTEN_PORT};
        listen [::]:${LISTEN_PORT};        
        root /usr/share/nginx/html;
        location /api/ {
            proxy_pass http://otrecorder/api/;
        }
        location /ws/ {
            proxy_pass http://otrecorder/ws/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection upgrade;
        }
        location / {
            include /etc/nginx/mime.types;
            try_files $uri $uri/index.html;
        }
        
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/javascript text/javascript;
        proxy_read_timeout 600;
    }
}
```
Finally, I added the directives from the [Running nginx as a non-root user](https://hub.docker.com/_/nginx#:~:text=Running%20nginx%20as%20a%20non%2Droot%20user) section of the [nginx official image](https://hub.docker.com/_/nginx) page on dockerhub.
```
pid        /tmp/nginx.pid;
worker_processes 1;
events {
    worker_connections 1024;
}
http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;
    upstream otrecorder {
        server ${SERVER_HOST}:${SERVER_PORT};
    }
    server {
        listen ${LISTEN_PORT};
        listen [::]:${LISTEN_PORT};        
        root /usr/share/nginx/html;
        location /api/ {
            proxy_pass http://otrecorder/api/;
        }
        location /ws/ {
            proxy_pass http://otrecorder/ws/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection upgrade;
        }
        location / {
            include /etc/nginx/mime.types;
            try_files $uri $uri/index.html;
        }
        
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/javascript text/javascript;
        proxy_read_timeout 600;
    }
}
```
This owntracks/frontend container starts and runs as my 121 non-root user as expected.

However, I do consider this a work-around given that if any updates are ever made in the nginx.tmpl file within the owntracks/frontend image, I would not automatically get them upon upgrade.

I am still of the opinion of adding the following directive to the nginx.tmpl file as part of the owntracks/frontend image would be the best long-term solution.
```
include /etc/nginx/conf.d/*.conf; 
```
