### ISSUE TITLE
Dawarich as an alternative to OwnTracks Frontend

### ISSUE THREAD

**Issue by linusg** [owntracks/frontend#160]
Today I found Dawarich: https://github.com/Freika/dawarich

> Self-hostable alternative to Google Location History (Google Maps Timeline)

Similar features have been requested and discussed in #48 and #121.

I have not tried it myself yet but it looks extremely promising. The [map view](https://dawarich.app/docs/features/map) alone does everything OwnTracks Frontend does (points, polyline, heatmap) and more (fog of war, as requested in #141). Other features include [Areas](https://dawarich.app/docs/features/areas) and [Trips](https://dawarich.app/docs/features/trips). It integrates with OwnTracks both for [existing data](https://dawarich.app/docs/tutorials/import-existing-data#owntracks-and-dawarich) and [recording new data](https://dawarich.app/docs/tutorials/track-your-location#owntracks).

Most crucially it is under active development (though by a single person). I still actively use OwnTracks but did not have time for development in recent years, let alone keeping up with the issue tracker and PRs. The Vue 2 to 3 migration is long overdue but would likely require a full rewrite. No other regular contributors exist, so **if Dawarich can replace OwnTracks Frontend for my purposes I will step down from maintainership** - at that point someone else can volunteer to keep the lights on or the repo will be archived.

The recorder's own UI will of course continue to exist and will be the recommended solution for people who only want to use OwnTracks without syncing data to a different software.

**Comment by jpmens** [comment]
> The recorder's own UI will of course continue to exist 

That UI is and has always been an awful hack and is nowhere near the quality and usability of Frontend which is why we use the latter only in, say, Quicksetup.

It'd be a bit of a shame to no longer have a maintained "OwnTracks Frontend".

**Comment by CthulhuDen** [comment]
Does somebody know if there's an easy way to make dawarich listen for updates in mqtt? I'd like to try it out but not without continuing writing data to owntracks recorder as well.

EDIT:

If anyone else is interested in setting something like that up, here I made really simple general purpose MQTT to HTTP bridge: https://github.com/CthulhuDen/mqtohttp

My config looks like this:

```yaml
  mqtohttp:
    image: ghcr.io/cthulhuden/mqtohttp:0.1
    restart: always
    environment:
      MQTT_ENDPOINT: <MQTT instance host with scheme>
      MQTT_USER: <user>
      MQTT_PASSWORD: <password>
      MQTT_TOPICS: owntracks/#
      HTTP_ENDPOINT: http://dawarich:3000/api/v1/owntracks/points?api_key=<API Key>
    volumes:
      - mqtohttp:/data
```
